using System.ComponentModel.DataAnnotations;

namespace MYAPI.Models.EXAPIDTOs;

public class AddressDTO
{
    [Key]
    public string Id { get; set; }                  // autogenerated
    public string City { get; set; }
    public string Street { get; set; }              // name + address
    public string ZipCode { get; set; }
    public string State { get; set; }

    public DateTime CreationDate { get; set; } 		//DB entry date
}
